version: '3.8'

services:
  web:
    image: odoo:18.0
    container_name: sattva-odoo-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=sattva_db_secure_pass
    restart: always
    networks:
      - sattva_cloud_net

  db:
    image: postgres:15-alpine
    container_name: sattva-odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=sattva_db_secure_pass
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - sattva_cloud_net

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  sattva_cloud_net:
    driver: bridge