from . import fabric_event
from . import res_partner
from . import purchase_order
from . import crm_lead
from . import vault
from . import notify
from . import order_handoff
from . import leadscore
from . import product_spec
from . import sattva_lot
from . import sale_order
from . import salehold
